name: Daily scrape of CloudProvider IP Ranges and updating the files in the repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-ip-ranges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: make build

      - name: Update all provider IP ranges
        run: make update

      - name: Commit and push if changed
        run: |
          git config user.name "AutomatedDailyUpdater"
          git config user.email "benji@no.reply"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update CloudProvider IpRanges: ${timestamp}" || exit 0
          git push
