name: ipscanner

on:
  push:
    paths:
      - 'ips_to_scan.txt'

jobs:
  scan_ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: make build

    - name: Scan IPs
      run: ./ip-to-cloudprovider scan-file ips_to_scan.txt -q > output.txt

    - name: Create issue
      run: |
        gh issue create \
          -t "IP Scan Results" \
          -b "$(cat output.txt)"
      env:
        GH_TOKEN: ${{ github.token }}
